---
- name: Remove apparmor
  apt:
    name: apparmor
    state: absent
  ignore_errors: yes

- name: Download Percona software repository
  get_url:
    url: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    dest: /tmp/percona-release_all.deb
    mode: 0440

- name: Install Percona software repository
  apt:
    deb: /tmp/percona-release_all.deb

- name: Run the percona-release
  shell: "{{ item }}"
  become: yes
  with_items:
    - percona-release disable all
    - percona-release setup pxc57
    - percona-release enable tools release
    - apt update -y

- name: Sets root password
  debconf:
    name: "percona-xtradb-cluster-57"
    question: "{{ item }}"
    value: "{{ root_password }}"
    vtype: 'password'
  changed_when: false
  with_items:
    - 'root_password'
    - 'root_password_again'

- name: Sets root password again
  debconf:
    name: "percona-xtradb-cluster-server-5.7"
    question: "percona-xtradb-cluster-server/{{ item }}"
    value: "{{ root_password }}"
    vtype: 'password'
  changed_when: false
  with_items:
    - 'root_password'
    - 'root_password_again'

- name: Configures for easy access as root user
  template:
    src: "../templates/root_my.cnf.j2"
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0400

- name: Install percona-server
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - percona-xtradb-cluster-full-57
    - python3-mysqldb
    - automysqlbackup

- name: Stop mysql on all node
  service:
    name: mysql
    state: stopped

- name: Adds mysql config
  template:
    src: "wsrep.cnf.j2"
    dest: "/etc/mysql/percona-xtradb-cluster.conf.d/wsrep.cnf"

- name: Bootstrap on master node
  command: /etc/init.d/mysql bootstrap-pxc
  when: mysql_bootstrap == True

- name: Create sst user
  mysql_user:
    name: "{{sst.user}}"
    password: "{{sst.pass}}"
    priv: "*.*:RELOAD,LOCK TABLES,PROCESS,REPLICATION CLIENT"
    host: localhost
    state: present
  when: mysql_bootstrap == True

- name: Restart mysql on other nodes
  command: /etc/init.d/mysql start
  when: mysql_bootstrap != True
